### PR TITLE
Add attribute for Equatable protocol

### PR DESCRIPTION
**Pull request by NiwakaDev**
This PR introduces the #[swift_bridge(Equatable)] attribute, which is used to generate a type that conforms to ```Equatable``` protocol.

Somthing like: 
```rust
// Rust 
mod ffi {
    extern "Rust" {
        #[swift_bridge(Equatable)]
        type SomeType;
    }
}
```

```Swift
// Generated Swift
class SomeType {
    // ...
}

// SomeType inherits SomeTypeRef. So, SomeType also conforms to Equatable protocol.
extension SomeTypeRef: Equatable {
    public static func == (lhs: SomeTypeRef, rhs: SomeTypeRef) -> Bool {
        __swift_bridge__$SomeTypeType$_partial_eq(rhs.ptr, lhs.ptr)
    }
}
```

### CODE REVIEW

**Review by chinedufn — APPROVED** [review]
Looks perfect. Tests look great. Thanks so much for your work here. Great stuff.

---

Can you just update your PR body with an example of the feature.

Here's an example: https://github.com/chinedufn/swift-bridge/pull/21

You can see more examples in the releases page https://github.com/chinedufn/swift-bridge/releases

Then I can merge this.

**Comment by NiwakaDev** [comment]
>Can you just update your PR body with an example of the feature.

I did this. Please check my PR body!

**Comment by NiwakaDev** [comment]
>Oh, and we need to add this to the attributes documentation here

I'll address this tomorrow!

**Comment by NiwakaDev** [comment]
Hi, @chinedufn!

I addressed your review.

**Comment by chinedufn** [comment]
Thanks!

**Comment by chinedufn** [comment]
Used this PR as a guide for #269 

Thanks!

**Pull request merged**
